<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $products = [

            // =========================
            // SKINCARE
            // =========================
            [
                'category_id' => 1,
                'name' => 'Ishira Soap',
                'slug' => 'ishira-soap',
                'description' => 'Premium cleansing soap formulated to refresh and nourish the skin.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-SOP-BASIC-ISH-001',
                'image' => 'ishira-soap.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Ishira Soap | Buy Original Skincare Soap in Nigeria – Cychez',
                'meta_description' => 'Shop original Ishira Soap at Cychez. Premium skincare cleansing soap. Affordable price, fast delivery across Nigeria.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 1,
                'name' => 'Medicube Collagen Night Wrapping Aqua Rich',
                'slug' => 'medicube-collagen-night-wrapping-aqua-rich',
                'description' => 'Deeply hydrating collagen night cream that restores skin elasticity overnight.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-CRM-COLL-MDC-001',
                'image' => 'medicube-collagen-night.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Medicube Collagen Night Cream | Buy Skincare in Nigeria – Cychez',
                'meta_description' => 'Shop Medicube Collagen Night Wrapping Aqua Rich at Cychez. Hydrating collagen cream for youthful skin. Fast delivery nationwide.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 1,
                'name' => 'Mooyam Kojic Acid & Turmeric',
                'slug' => 'mooyam-kojic-acid-turmeric',
                'description' => 'Brightening skincare product formulated with kojic acid and turmeric.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-CRM-KOJ-MOO-001',
                'image' => 'mooyam-kojic.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Mooyam Kojic Acid & Turmeric | Buy Skincare in Nigeria – Cychez',
                'meta_description' => 'Shop Mooyam Kojic Acid & Turmeric at Cychez. Brightening skincare solution for even-toned skin. Nationwide delivery available.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 1,
                'name' => 'Dr Rashel Vitamin C Face Serum',
                'slug' => 'dr-rashel-vitamin-c-face-serum',
                'description' => 'Vitamin C serum that brightens skin and improves overall complexion.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-SER-VITC-DRR-001',
                'image' => 'dr-rashel-vitamin-c.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Dr Rashel Vitamin C Serum | Buy Face Serum in Nigeria – Cychez',
                'meta_description' => 'Shop Dr Rashel Vitamin C Face Serum at Cychez. Brightening serum for radiant skin. Affordable price and fast delivery.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 1,
                'name' => 'Biore UV Watery Essence',
                'slug' => 'biore-uv-watery-essence',
                'description' => 'Lightweight sunscreen that provides effective UV protection without greasy feel.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-SUN-UV-BIO-001',
                'image' => 'biore-uv-watery.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Biore UV Watery Essence | Buy Sunscreen in Nigeria – Cychez',
                'meta_description' => 'Shop Biore UV Watery Essence at Cychez. Lightweight sunscreen with strong UV protection. Fast delivery across Nigeria.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 1,
                'name' => 'Beauty Formulas Brightening Vitamin Cleanser',
                'slug' => 'beauty-formulas-brightening-vitamin-cleanser',
                'description' => 'Brightening facial cleanser enriched with vitamins for radiant skin.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-CLN-VIT-BEF-001',
                'image' => 'beauty-formulas-vitamin-cleanser.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Beauty Formulas Vitamin Cleanser | Buy Face Wash in Nigeria – Cychez',
                'meta_description' => 'Shop Beauty Formulas Brightening Vitamin Cleanser at Cychez. Gently cleanses and brightens skin. Fast delivery nationwide.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 1,
                'name' => 'Dermaliss Facial Cleanser',
                'slug' => 'dermaliss-facial-cleanser',
                'description' => 'Gentle facial cleanser suitable for daily skincare routine.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-CLN-BASIC-DER-001',
                'image' => 'dermaliss-cleanser.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Dermaliss Facial Cleanser | Buy Skincare Cleanser in Nigeria – Cychez',
                'meta_description' => 'Shop Dermaliss Facial Cleanser at Cychez. Gentle daily cleanser for healthy skin. Affordable and reliable delivery.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 1,
                'name' => 'Estelin Whitening Toner',
                'slug' => 'estelin-whitening-toner',
                'description' => 'Brightening toner that helps improve skin tone and texture.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-TON-WHITE-EST-001',
                'image' => 'estelin-toner.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Estelin Whitening Toner | Buy Face Toner in Nigeria – Cychez',
                'meta_description' => 'Shop Estelin Whitening Toner at Cychez. Helps brighten and refresh skin. Fast delivery across Nigeria.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 1,
                'name' => 'Active Caviar Drip Toner',
                'slug' => 'active-caviar-drip-toner',
                'description' => 'Luxury toner infused with caviar extract for skin rejuvenation.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-TON-CAV-ACT-001',
                'image' => 'active-caviar-toner.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Active Caviar Drip Toner | Buy Luxury Skincare in Nigeria – Cychez',
                'meta_description' => 'Shop Active Caviar Drip Toner at Cychez. Luxury skincare toner for youthful glowing skin. Nationwide delivery.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 1,
                'name' => 'Bioaqua Rice Raw Pulp Facial Mask',
                'slug' => 'bioaqua-rice-raw-pulp-facial-mask',
                'description' => 'Hydrating and brightening facial mask with rice extract.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-MSK-RICE-BIO-001',
                'image' => 'bioaqua-rice-mask.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Bioaqua Rice Facial Mask | Buy Face Mask in Nigeria – Cychez',
                'meta_description' => 'Shop Bioaqua Rice Raw Pulp Facial Mask at Cychez. Hydrating mask for smooth radiant skin.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 1,
                'name' => 'Estelin 5D Hyaluronic Acid Serum',
                'slug' => 'estelin-5d-hyaluronic-acid-serum',
                'description' => 'Deep hydration serum with 5D hyaluronic acid for plump skin.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-SER-HYA-EST-001',
                'image' => 'estelin-5d-hyaluronic.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Estelin 5D Hyaluronic Acid Serum | Buy Serum in Nigeria – Cychez',
                'meta_description' => 'Shop Estelin 5D Hyaluronic Acid Serum at Cychez. Deep hydration for smooth youthful skin.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 1,
                'name' => 'Face Facts Glow + Resurface Serum',
                'slug' => 'face-facts-glow-resurface-serum',
                'description' => 'Glow-enhancing serum that improves skin texture and radiance.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-SER-GLOW-FFC-001',
                'image' => 'face-facts-glow.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Face Facts Glow Serum | Buy Skincare in Nigeria – Cychez',
                'meta_description' => 'Shop Face Facts Glow + Resurface Serum at Cychez. Smooth, radiant, glowing skin.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 1,
                'name' => 'COSRX Advanced Snail 92 All In One Cream',
                'slug' => 'cosrx-advanced-snail-92-cream',
                'description' => 'Snail mucin cream for intense skin repair and hydration.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-CRM-SNAIL-COS-001',
                'image' => 'cosrx-snail-cream.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'COSRX Snail 92 Cream | Buy Face Cream in Nigeria – Cychez',
                'meta_description' => 'Shop COSRX Advanced Snail 92 Cream at Cychez. Deep repair and hydration for healthy skin.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 1,
                'name' => 'Beauty Skin Free Glutathione Vitamin C Face Cream',
                'slug' => 'beauty-skin-free-glutathione-vitamin-c-cream',
                'description' => 'Brightening face cream with glutathione and vitamin C.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-CRM-GLUT-BSF-001',
                'image' => 'beauty-skin-free-cream.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Glutathione Vitamin C Cream | Buy Face Cream in Nigeria – Cychez',
                'meta_description' => 'Shop Beauty Skin Free Glutathione Vitamin C Face Cream at Cychez. Brighter, even-toned skin.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 1,
                'name' => 'Menarini Tretinoin Gel USP 0.025% Acne Removal',
                'slug' => 'menarini-tretinoin-gel-0025-acne',
                'description' => 'Dermatological tretinoin gel formulated for acne treatment and skin renewal.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 50,
                'sku' => 'SK-GEL-ACNE-MEN-001',
                'image' => 'menarini-tretinoin-0025.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Menarini Tretinoin Gel 0.025% | Acne Treatment in Nigeria – Cychez',
                'meta_description' => 'Shop Menarini Tretinoin Gel 0.025% at Cychez. Effective acne treatment for clearer skin.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 1,
                'name' => 'Menarini Tretinoin Gel USP 0.1% Stretch Mark Treatment',
                'slug' => 'menarini-tretinoin-gel-01-stretch-mark',
                'description' => 'High-strength tretinoin gel designed to improve stretch marks and skin texture.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 50,
                'sku' => 'SK-GEL-REPAIR-MEN-002',
                'image' => 'menarini-tretinoin-01.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Menarini Tretinoin Gel 0.1% | Stretch Mark Treatment – Cychez',
                'meta_description' => 'Shop Menarini Tretinoin Gel 0.1% at Cychez. Advanced treatment for stretch marks.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 1,
                'name' => 'Dark Spot Correcting Glow Serum (Korean, Vegan)',
                'slug' => 'dark-spot-correcting-glow-serum-korean-vegan',
                'description' => 'Korean vegan serum formulated to fade dark spots and enhance skin glow.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-SER-SPOT-KOR-001',
                'image' => 'dark-spot-glow-serum.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Dark Spot Correcting Glow Serum | Buy Korean Skincare – Cychez',
                'meta_description' => 'Shop Dark Spot Correcting Glow Serum at Cychez. Vegan Korean serum for brighter skin.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 1,
                'name' => 'Bioaqua Salicylic Acid Acne Removal Cream',
                'slug' => 'bioaqua-salicylic-acid-acne-cream',
                'description' => 'Salicylic acid cream that helps fight acne and unclog pores.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-CRM-ACNE-BIO-001',
                'image' => 'bioaqua-salicylic-acid.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Bioaqua Salicylic Acid Cream | Acne Treatment Nigeria – Cychez',
                'meta_description' => 'Shop Bioaqua Salicylic Acid Acne Removal Cream at Cychez. Clearer skin starts here.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 1,
                'name' => 'Kojivit Ultra Gel',
                'slug' => 'kojivit-ultra-gel',
                'description' => 'Advanced depigmenting gel for dark spots and uneven skin tone.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-GEL-PIGM-KOJ-001',
                'image' => 'kojivit-ultra-gel.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Kojivit Ultra Gel | Dark Spot Treatment in Nigeria – Cychez',
                'meta_description' => 'Shop Kojivit Ultra Gel at Cychez. Effective solution for dark spots and pigmentation.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 1,
                'name' => 'Chavah Beauty Second Skin Long Wear Foundation',
                'slug' => 'chavah-beauty-second-skin-foundation',
                'description' => 'Long-wear foundation with a natural second-skin finish.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-FND-LONG-CHV-001',
                'image' => 'chavah-second-skin.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Chavah Beauty Second Skin Foundation | Buy in Nigeria – Cychez',
                'meta_description' => 'Shop Chavah Beauty Second Skin Long Wear Foundation at Cychez. Flawless natural coverage.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 1,
                'name' => 'Artistry Full Coverage Matte Foundation (Oil Free)',
                'slug' => 'artistry-full-coverage-matte-foundation',
                'description' => 'Oil-free matte foundation with full coverage and smooth finish.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-FND-MATTE-ART-001',
                'image' => 'artistry-matte-foundation.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Artistry Matte Foundation | Full Coverage Makeup Nigeria – Cychez',
                'meta_description' => 'Shop Artistry Full Coverage Matte Foundation at Cychez. Oil-free flawless makeup.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 1,
                'name' => 'P-Kay USA Foundation',
                'slug' => 'p-kay-usa-foundation',
                'description' => 'Professional foundation formulated for smooth, even coverage.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-FND-PRO-PKY-001',
                'image' => 'p-kay-foundation.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'P-Kay USA Foundation | Buy Foundation in Nigeria – Cychez',
                'meta_description' => 'Shop P-Kay USA Foundation at Cychez. Professional makeup with smooth coverage.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 1,
                'name' => 'MyChic Cosmetics New York Foundation',
                'slug' => 'mychic-cosmetics-new-york-foundation',
                'description' => 'New York-inspired foundation with flawless long-lasting coverage.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-FND-NYC-MYC-001',
                'image' => 'mychic-ny-foundation.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'MyChic New York Foundation | Buy Makeup in Nigeria – Cychez',
                'meta_description' => 'Shop MyChic Cosmetics New York Foundation at Cychez. Smooth flawless coverage.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 1,
                'name' => 'Mac Bucci Italian Foundation',
                'slug' => 'mac-bucci-italian-foundation',
                'description' => 'Italian-made foundation for refined and elegant makeup finish.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-FND-ITAL-MAC-001',
                'image' => 'mac-bucci-foundation.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Mac Bucci Italian Foundation | Buy Makeup Nigeria – Cychez',
                'meta_description' => 'Shop Mac Bucci Italian Foundation at Cychez. Elegant European makeup coverage.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 1,
                'name' => 'Vee BecuIty Stay Matte Makeup',
                'slug' => 'vee-becutiy-stay-matte-makeup',
                'description' => 'Stay-matte makeup for oil control and long-lasting finish.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-MUP-MATTE-VEE-001',
                'image' => 'vee-becutiy-matte.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Vee BecuIty Stay Matte Makeup | Buy Makeup Nigeria – Cychez',
                'meta_description' => 'Shop Vee BecuIty Stay Matte Makeup at Cychez. Long-lasting matte finish.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 1,
                'name' => 'Primer Base de Maquillage 003',
                'slug' => 'primer-base-de-maquillage-003',
                'description' => 'Makeup primer that smoothens skin and improves makeup longevity.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'SK-PRM-SMOOTH-PRM-001',
                'image' => 'primer-base-003.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Primer Base de Maquillage 003 | Buy Makeup Primer Nigeria – Cychez',
                'meta_description' => 'Shop Primer Base de Maquillage 003 at Cychez. Smooth base for flawless makeup.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =========================
            // MAKEUP
            // =========================

            [
                'category_id' => 2,
                'name' => 'Facebeat Studiofix Foundation',
                'slug' => 'facebeat-studiofix-foundation',
                'description' => 'Professional studio-finish foundation for flawless coverage.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'MU-FND-FULL-FBE-001',
                'image' => 'facebeat-studiofix.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Facebeat Studiofix Foundation | Buy Makeup in Nigeria – Cychez',
                'meta_description' => 'Shop Facebeat Studiofix Foundation at Cychez. Full coverage foundation for a flawless look.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 2,
                'name' => 'Issa & Dose Mattifying Compact Powder',
                'slug' => 'issa-dose-mattifying-compact-powder',
                'description' => 'Mattifying compact powder for shine-free makeup finish.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'MU-POW-MAT-ISS-001',
                'image' => 'issa-dose-compact.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Issa & Dose Compact Powder | Buy Makeup in Nigeria – Cychez',
                'meta_description' => 'Shop Issa & Dose Mattifying Compact Powder at Cychez. Long-lasting matte finish.',
                'created_at' => $now,
                'updated_at' => $now,
            ],


            // =========================
            // ACCESSORIES
            // =========================
            [
                'category_id' => 6,
                'name' => 'Blossom Makeup Eyelash Adhesive Glue',
                'slug' => 'blossom-makeup-eyelash-adhesive-glue',
                'description' => 'Strong hold eyelash adhesive for all lash types.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'AC-LAS-GLUE-BLO-001',
                'image' => 'blossom-lash-glue.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Blossom Eyelash Glue | Buy Lash Accessories in Nigeria – Cychez',
                'meta_description' => 'Shop Blossom Makeup Eyelash Adhesive Glue at Cychez. Strong, reliable lash hold.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 6,
                'name' => 'Fresh Look Color Blends Contact Lens',
                'slug' => 'fresh-look-color-blends-contact-lens',
                'description' => 'Soft cosmetic contact lenses for natural eye enhancement.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 50,
                'sku' => 'AC-CNT-COLOR-FRL-001',
                'image' => 'fresh-look-lens.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Fresh Look Color Contact Lens | Buy Contact Lens in Nigeria – Cychez',
                'meta_description' => 'Shop Fresh Look Color Blends Contact Lens at Cychez. Comfortable cosmetic lenses.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 6,
                'name' => 'Paper Crane Premium Press-On Nails',
                'slug' => 'paper-crane-premium-press-on-nails',
                'description' => 'Premium quality press-on nails with elegant finish.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 80,
                'sku' => 'AC-NAL-PREM-PCR-001',
                'image' => 'paper-crane-nails.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Paper Crane Press-On Nails | Buy Nails in Nigeria – Cychez',
                'meta_description' => 'Shop Paper Crane Premium Press-On Nails at Cychez. Stylish, easy-to-wear nails.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =========================
            // FRAGRANCES
            // =========================

            [
                'category_id' => 4,
                'name' => 'Lattafa Khamarah',
                'slug' => 'lattafa-khamarah',
                'description' => 'Luxury unisex fragrance with rich, long-lasting scent.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 50,
                'sku' => 'FR-PRF-SPICE-LAT-001',
                'image' => 'lattafa-khamarah.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Lattafa Khamarah Perfume | Buy Original Fragrance in Nigeria – Cychez',
                'meta_description' => 'Shop Lattafa Khamarah at Cychez. Luxury unisex fragrance with long-lasting scent. Fast nationwide delivery.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 4,
                'name' => 'Rouge Perfume',
                'slug' => 'rouge-perfume',
                'description' => 'Elegant fragrance with a bold and captivating scent profile.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 50,
                'sku' => 'FR-PRF-BOLD-ROU-001',
                'image' => 'rouge.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Rouge Perfume | Buy Original Fragrance in Nigeria – Cychez',
                'meta_description' => 'Shop Rouge Perfume at Cychez. Bold, elegant fragrance with long-lasting scent. Fast delivery across Nigeria.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 4,
                'name' => 'Avanti Perfume',
                'slug' => 'avanti-perfume',
                'description' => 'Classic fragrance designed for everyday sophistication.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 50,
                'sku' => 'FR-PRF-CLASS-AVA-001',
                'image' => 'avanti.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Avanti Perfume | Buy Original Fragrance in Nigeria – Cychez',
                'meta_description' => 'Shop Avanti Perfume at Cychez. A classic fragrance for daily wear. Nationwide delivery available.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 4,
                'name' => 'Eclaire Perfume',
                'slug' => 'eclaire-perfume',
                'description' => 'Soft and radiant fragrance with a luxurious finish.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 50,
                'sku' => 'FR-PRF-SOFT-ECL-001',
                'image' => 'eclaire.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Eclaire Perfume | Buy Original Fragrance in Nigeria – Cychez',
                'meta_description' => 'Shop Eclaire Perfume at Cychez. Soft, radiant fragrance with lasting appeal.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 4,
                'name' => 'Asad Zanzibar by Lattafa',
                'slug' => 'asad-zanzibar-lattafa',
                'description' => 'Bold masculine fragrance with deep spicy and woody notes.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 50,
                'sku' => 'FR-PRF-MUSK-LAT-002',
                'image' => 'asad-zanzibar.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Asad Zanzibar Perfume | Buy Lattafa Fragrance in Nigeria – Cychez',
                'meta_description' => 'Shop Asad Zanzibar by Lattafa at Cychez. Bold masculine fragrance with lasting intensity.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 4,
                'name' => 'Berries Weekend Pink Edition',
                'slug' => 'berries-weekend-pink-edition',
                'description' => 'Sweet and playful fragrance with fruity floral notes.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 50,
                'sku' => 'FR-PRF-FRUITY-BWP-001',
                'image' => 'berries-weekend-pink.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Berries Weekend Pink Edition | Buy Fragrance in Nigeria – Cychez',
                'meta_description' => 'Shop Berries Weekend Pink Edition at Cychez. Sweet fruity fragrance with feminine charm.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 4,
                'name' => 'Aromax Aroma Expert Sugar',
                'slug' => 'aromax-aroma-expert-sugar',
                'description' => 'Sweet gourmand fragrance with sugary aroma notes.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 50,
                'sku' => 'FR-PRF-SWEET-ARX-001',
                'image' => 'aromax-sugar.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Aromax Aroma Expert Sugar | Buy Sweet Fragrance in Nigeria – Cychez',
                'meta_description' => 'Shop Aromax Aroma Expert Sugar at Cychez. Sweet gourmand fragrance with lasting scent.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 4,
                'name' => 'Aro-Fac Aroma Factory Sugar Pink',
                'slug' => 'aro-fac-aroma-factory-sugar-pink',
                'description' => 'Sweet pink fragrance with playful and youthful notes.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 50,
                'sku' => 'FR-PRF-SWEET-AFC-001',
                'image' => 'aro-fac-sugar-pink.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Aro-Fac Sugar Pink Perfume | Buy Fragrance in Nigeria – Cychez',
                'meta_description' => 'Shop Aro-Fac Aroma Factory Sugar Pink at Cychez. Sweet playful fragrance with charm.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 4,
                'name' => 'Imperior Way Parfum',
                'slug' => 'imperior-way-parfum',
                'description' => 'Premium parfum with a powerful and refined scent.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 50,
                'sku' => 'FR-PRF-PREM-IMP-001',
                'image' => 'imperior-way.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Imperior Way Parfum | Buy Luxury Fragrance in Nigeria – Cychez',
                'meta_description' => 'Shop Imperior Way Parfum at Cychez. Premium fragrance with refined long-lasting scent.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 4,
                'name' => '9PM – 6PM Perfume',
                'slug' => '9pm-6pm-perfume',
                'description' => 'Versatile fragrance suitable for day-to-night wear.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 50,
                'sku' => 'FR-PRF-DAYNITE-9PM-001',
                'image' => '9pm-6pm.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => '9PM – 6PM Perfume | Buy Fragrance in Nigeria – Cychez',
                'meta_description' => 'Shop 9PM – 6PM Perfume at Cychez. Perfect fragrance for day and night use.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'category_id' => 4,
                'name' => 'Kaly Perfume',
                'slug' => 'kaly-perfume',
                'description' => 'Modern fragrance with a clean and attractive scent.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 50,
                'sku' => 'FR-PRF-MODERN-KAL-001',
                'image' => 'kaly.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Kaly Perfume | Buy Original Fragrance in Nigeria – Cychez',
                'meta_description' => 'Shop Kaly Perfume at Cychez. Modern fragrance with a clean, lasting scent.',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // =========================
            // BODY CARE
            // =========================

            [
                'category_id' => 5,
                'name' => 'Dove Calming Body Wash',
                'slug' => 'dove-calming-body-wash',
                'description' => 'Gentle body wash designed to soothe and moisturize skin.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'BC-CLN-CALM-DOV-001',
                'image' => 'dove-calming-body-wash.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Dove Calming Body Wash | Buy Body Care in Nigeria – Cychez',
                'meta_description' => 'Shop Dove Calming Body Wash at Cychez. Gentle cleansing for soft, calm skin. Affordable price and fast delivery.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 5,
                'name' => 'St Ives Hydrating Body Wash Coconut Water & Orchid',
                'slug' => 'st-ives-hydrating-body-wash-coconut-orchid',
                'description' => 'Hydrating body wash infused with coconut water and orchid.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'BC-CLN-HYDR-STI-001',
                'image' => 'st-ives-body-wash.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'St Ives Hydrating Body Wash | Buy Body Care in Nigeria – Cychez',
                'meta_description' => 'Shop St Ives Hydrating Body Wash at Cychez. Refreshing hydration for soft skin.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 5,
                'name' => 'Sure Deodorant',
                'slug' => 'sure-deodorant',
                'description' => 'Long-lasting deodorant for all-day freshness.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 100,
                'sku' => 'BC-DEO-FRESH-SUR-001',
                'image' => 'sure-deodorant.jpg',
                'images' => null,
                'is_featured' => 0,
                'is_active' => 1,
                'meta_title' => 'Sure Deodorant | Buy Deodorant in Nigeria – Cychez',
                'meta_description' => 'Shop Sure Deodorant at Cychez. Reliable odor protection all day long.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 3,
                'name' => 'Mega Growth No-Lye Relaxer Salon Pack',
                'slug' => 'mega-growth-no-lye-relaxer',
                'description' => 'Advanced strengthening no-lye hair relaxer for salon results.',
                'price' => 5000,
                'compare_price' => 6500,
                'cost_price' => null,
                'stock_quantity' => 50,
                'sku' => 'HC-TRT-RELAX-MEG-001',
                'image' => 'mega-growth-relaxer.jpg',
                'images' => null,
                'is_featured' => 1,
                'is_active' => 1,
                'meta_title' => 'Mega Growth No Lye Relaxer | Buy Haircare in Nigeria – Cychez',
                'meta_description' => 'Shop Mega Growth No-Lye Relaxer at Cychez. Stronger, healthier relaxed hair.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id'     => 5,
                'name'            => 'Asantee Gluta Papaya Arbutin Kojic Papaya Carrot Face & Body Soap',
                'slug'            => 'asantee-gluta-papaya-arbutin-kojic-carrot-soap',
                'description'     => 'Asantee Gluta Papaya and Kojic infused carrot face and body soap for brightening and clarifying skin.',
                'price'           => 5000,
                'compare_price'   => 6500,
                'cost_price'      => null,
                'stock_quantity'  => 0,
                'sku'             => 'BC-SOP-GLUT-ASAN-001',
                'image'           => null,
                'images'          => null,
                'is_featured'     => 0,
                'is_active'       => 1,
                'meta_title'      => 'Asantee Gluta Papaya Kojic Carrot Soap',
                'meta_description'=> 'Brightening gluta papaya and kojic body and face soap by Asantee.',
            ],

            [
                'category_id'     => 5,
                'name'            => 'K.Brothers USA Papaya Soap',
                'slug'            => 'k-brothers-usa-papaya-soap',
                'description'     => 'K.Brothers USA papaya soap for clearer, smoother and radiant skin tone.',
                'price'           => 5000,
                'compare_price'   => 6500,
                'cost_price'      => null,
                'stock_quantity'  => 0,
                'sku'             => 'BC-SOP-PAP-KBR-002',
                'image'           => null,
                'images'          => null,
                'is_featured'     => 0,
                'is_active'       => 1,
                'meta_title'      => 'K.Brothers USA Papaya Soap',
                'meta_description'=> 'Original K.Brothers USA papaya brightening and smoothing soap.',
            ],

            [
                'category_id'     => 5,
                'name'            => 'Parley Goldie Halfcast Lightening Soap',
                'slug'            => 'parley-goldie-halfcast-lightening-soap',
                'description'     => 'Parley Goldie Halfcast lightening soap for glowing and radiant skin complexion.',
                'price'           => 5000,
                'compare_price'   => 6500,
                'cost_price'      => null,
                'stock_quantity'  => 0,
                'sku'             => 'BC-SOP-GOLD-PAR-003',
                'image'           => null,
                'images'          => null,
                'is_featured'     => 0,
                'is_active'       => 1,
                'meta_title'      => 'Parley Goldie Halfcast Lightening Soap',
                'meta_description'=> 'Halfcast brightening and glow body soap by Parley.',
            ],

            [
                'category_id'     => 5,
                'name'            => 'D-NE Gold Nano Extra White Turmeric & Honey Soap',
                'slug'            => 'd-ne-gold-nano-extra-white-turmeric-honey-soap',
                'description'     => 'D-NE Gold Nano Extra White soap with turmeric and honey for brightening and nourishing skin.',
                'price'           => 5000,
                'compare_price'   => 6500,
                'cost_price'      => null,
                'stock_quantity'  => 0,
                'sku'             => 'BC-SOP-TURM-DNE-004',
                'image'           => null,
                'images'          => null,
                'is_featured'     => 0,
                'is_active'       => 1,
                'meta_title'      => 'D-NE Gold Nano Extra White Turmeric Honey Soap',
                'meta_description'=> 'Turmeric and honey nano whitening body soap by D-NE Gold.',
            ],

            [
                'category_id'     => 5,
                'name'            => 'Jennifer Lopez Secrets Transparent Complexion Cleansing Bar',
                'slug'            => 'jennifer-lopez-secrets-transparent-cleansing-bar',
                'description'     => 'Jennifer Lopez Secrets transparent complexion cleansing bar for smooth, clear skin.',
                'price'           => 5000,
                'compare_price'   => 6500,
                'cost_price'      => null,
                'stock_quantity'  => 0,
                'sku'             => 'BC-SOP-CLAR-JLO-005',
                'image'           => null,
                'images'          => null,
                'is_featured'     => 0,
                'is_active'       => 1,
                'meta_title'      => 'Jennifer Lopez Secrets Cleansing Bar',
                'meta_description'=> 'Transparent complexion cleansing bar by Jennifer Lopez Secrets.',
            ],

            [
                'category_id'     => 5,
                'name'            => 'Dove Pink / Rosa Beauty Bar',
                'slug'            => 'dove-pink-rosa-beauty-bar',
                'description'     => 'Dove Pink / Rosa moisturizing beauty bar for soft and smooth skin.',
                'price'           => 5000,
                'compare_price'   => 6500,
                'cost_price'      => null,
                'stock_quantity'  => 0,
                'sku'             => 'BC-SOP-PINK-DOV-006',
                'image'           => null,
                'images'          => null,
                'is_featured'     => 0,
                'is_active'       => 1,
                'meta_title'      => 'Dove Pink Rosa Beauty Bar',
                'meta_description'=> 'Moisturizing Dove Pink / Rosa body and face soap.',
            ],

            [
                'category_id'     => 5,
                'name'            => 'Olay Triple Glow Pure Whitening Soap',
                'slug'            => 'olay-triple-glow-pure-whitening-soap',
                'description'     => 'Olay Triple Glow pure whitening body soap for bright, radiant and even-toned skin.',
                'price'           => 5000,
                'compare_price'   => 6500,
                'cost_price'      => null,
                'stock_quantity'  => 0,
                'sku'             => 'BC-SOP-GLOW-OLY-007',
                'image'           => null,
                'images'          => null,
                'is_featured'     => 0,
                'is_active'       => 1,
                'meta_title'      => 'Olay Triple Glow Whitening Soap',
                'meta_description'=> 'Brightening and glow soap by Olay Triple Glow.',
            ],

            [
                'category_id'     => 5,
                'name'            => 'Ayirah Gold Carrot Soap',
                'slug'            => 'ayirah-gold-carrot-soap',
                'description'     => 'Ayirah Gold carrot soap formulated to brighten and nourish dull skin.',
                'price'           => 5000,
                'compare_price'   => 6500,
                'cost_price'      => null,
                'stock_quantity'  => 0,
                'sku'             => 'BC-SOP-CART-AYR-008',
                'image'           => null,
                'images'          => null,
                'is_featured'     => 0,
                'is_active'       => 1,
                'meta_title'      => 'Ayirah Gold Carrot Soap',
                'meta_description'=> 'Carrot brightening body soap by Ayirah Gold.',
            ],

            [
                'category_id'     => 5,
                'name'            => "Nature Secrete Argan Exfoliating Lightening Soap",
                'slug'            => 'nature-secrete-argan-exfoliating-lightening-soap',
                'description'     => "Nature Secrete Argan exfoliating and lightening soap for smooth, radiant skin.",
                'price'           => 5000,
                'compare_price'   => 6500,
                'cost_price'      => null,
                'stock_quantity'  => 0,
                'sku'             => 'BC-SOP-ARGN-NSC-009',
                'image'           => null,
                'images'          => null,
                'is_featured'     => 0,
                'is_active'       => 1,
                'meta_title'      => 'Nature Secrete Argan Exfoliating Soap',
                'meta_description'=> 'Argan oil exfoliating and lightening soap by Nature Secrete.',
            ],

            [
                'category_id'     => 5,
                'name'            => 'Dermatological E45 Skin Nourishing Soap 2-in-1',
                'slug'            => 'e45-skin-nourishing-soap-2-in-1',
                'description'     => 'Dermatological E45 skin nourishing 2-in-1 soft skin soap for dry and sensitive skin.',
                'price'           => 5000,
                'compare_price'   => 6500,
                'cost_price'      => null,
                'stock_quantity'  => 0,
                'sku'             => 'BC-SOP-NRSH-E45-010',
                'image'           => null,
                'images'          => null,
                'is_featured'     => 0,
                'is_active'       => 1,
                'meta_title'      => 'E45 Skin Nourishing Soap',
                'meta_description'=> 'Dermatological E45 2-in-1 nourishing soft skin soap.',
            ],

        ];

        foreach ($products as $index => $product) {
            try {
                $this->db->table('products')->insert($product);
            } catch (\Throwable $e) {
                echo "\n❌ Error at product index: {$index}\n";
                print_r($product);
                die("\n" . $e->getMessage() . "\n");
            }
        }
    }
}